// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: cafesdk/sdk.proto

package cafesdk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParameterClient is the client API for Parameter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParameterClient interface {
	GetInputJSONString(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InputJSONStringResponse, error)
}

type parameterClient struct {
	cc grpc.ClientConnInterface
}

func NewParameterClient(cc grpc.ClientConnInterface) ParameterClient {
	return &parameterClient{cc}
}

func (c *parameterClient) GetInputJSONString(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InputJSONStringResponse, error) {
	out := new(InputJSONStringResponse)
	err := c.cc.Invoke(ctx, "/cafesdk.Parameter/GetInputJSONString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParameterServer is the server API for Parameter service.
// All implementations must embed UnimplementedParameterServer
// for forward compatibility
type ParameterServer interface {
	GetInputJSONString(context.Context, *emptypb.Empty) (*InputJSONStringResponse, error)
	mustEmbedUnimplementedParameterServer()
}

// UnimplementedParameterServer must be embedded to have forward compatible implementations.
type UnimplementedParameterServer struct {
}

func (UnimplementedParameterServer) GetInputJSONString(context.Context, *emptypb.Empty) (*InputJSONStringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInputJSONString not implemented")
}
func (UnimplementedParameterServer) mustEmbedUnimplementedParameterServer() {}

// UnsafeParameterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParameterServer will
// result in compilation errors.
type UnsafeParameterServer interface {
	mustEmbedUnimplementedParameterServer()
}

func RegisterParameterServer(s grpc.ServiceRegistrar, srv ParameterServer) {
	s.RegisterService(&Parameter_ServiceDesc, srv)
}

func _Parameter_GetInputJSONString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParameterServer).GetInputJSONString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cafesdk.Parameter/GetInputJSONString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParameterServer).GetInputJSONString(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Parameter_ServiceDesc is the grpc.ServiceDesc for Parameter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Parameter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cafesdk.Parameter",
	HandlerType: (*ParameterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInputJSONString",
			Handler:    _Parameter_GetInputJSONString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cafesdk/sdk.proto",
}

// ResultClient is the client API for Result service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResultClient interface {
	SetTableHeader(ctx context.Context, in *TableHeader, opts ...grpc.CallOption) (*Response, error)
	PushData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Response, error)
}

type resultClient struct {
	cc grpc.ClientConnInterface
}

func NewResultClient(cc grpc.ClientConnInterface) ResultClient {
	return &resultClient{cc}
}

func (c *resultClient) SetTableHeader(ctx context.Context, in *TableHeader, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/cafesdk.Result/SetTableHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resultClient) PushData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/cafesdk.Result/PushData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResultServer is the server API for Result service.
// All implementations must embed UnimplementedResultServer
// for forward compatibility
type ResultServer interface {
	SetTableHeader(context.Context, *TableHeader) (*Response, error)
	PushData(context.Context, *Data) (*Response, error)
	mustEmbedUnimplementedResultServer()
}

// UnimplementedResultServer must be embedded to have forward compatible implementations.
type UnimplementedResultServer struct {
}

func (UnimplementedResultServer) SetTableHeader(context.Context, *TableHeader) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTableHeader not implemented")
}
func (UnimplementedResultServer) PushData(context.Context, *Data) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushData not implemented")
}
func (UnimplementedResultServer) mustEmbedUnimplementedResultServer() {}

// UnsafeResultServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResultServer will
// result in compilation errors.
type UnsafeResultServer interface {
	mustEmbedUnimplementedResultServer()
}

func RegisterResultServer(s grpc.ServiceRegistrar, srv ResultServer) {
	s.RegisterService(&Result_ServiceDesc, srv)
}

func _Result_SetTableHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableHeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResultServer).SetTableHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cafesdk.Result/SetTableHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResultServer).SetTableHeader(ctx, req.(*TableHeader))
	}
	return interceptor(ctx, in, info, handler)
}

func _Result_PushData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResultServer).PushData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cafesdk.Result/PushData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResultServer).PushData(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// Result_ServiceDesc is the grpc.ServiceDesc for Result service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Result_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cafesdk.Result",
	HandlerType: (*ResultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTableHeader",
			Handler:    _Result_SetTableHeader_Handler,
		},
		{
			MethodName: "PushData",
			Handler:    _Result_PushData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cafesdk/sdk.proto",
}

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogClient interface {
	Debug(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error)
	Info(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error)
	Warn(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error)
	Error(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error)
}

type logClient struct {
	cc grpc.ClientConnInterface
}

func NewLogClient(cc grpc.ClientConnInterface) LogClient {
	return &logClient{cc}
}

func (c *logClient) Debug(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/cafesdk.Log/Debug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) Info(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/cafesdk.Log/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) Warn(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/cafesdk.Log/Warn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) Error(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/cafesdk.Log/Error", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServer is the server API for Log service.
// All implementations must embed UnimplementedLogServer
// for forward compatibility
type LogServer interface {
	Debug(context.Context, *LogBody) (*Response, error)
	Info(context.Context, *LogBody) (*Response, error)
	Warn(context.Context, *LogBody) (*Response, error)
	Error(context.Context, *LogBody) (*Response, error)
	mustEmbedUnimplementedLogServer()
}

// UnimplementedLogServer must be embedded to have forward compatible implementations.
type UnimplementedLogServer struct {
}

func (UnimplementedLogServer) Debug(context.Context, *LogBody) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Debug not implemented")
}
func (UnimplementedLogServer) Info(context.Context, *LogBody) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedLogServer) Warn(context.Context, *LogBody) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Warn not implemented")
}
func (UnimplementedLogServer) Error(context.Context, *LogBody) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Error not implemented")
}
func (UnimplementedLogServer) mustEmbedUnimplementedLogServer() {}

// UnsafeLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServer will
// result in compilation errors.
type UnsafeLogServer interface {
	mustEmbedUnimplementedLogServer()
}

func RegisterLogServer(s grpc.ServiceRegistrar, srv LogServer) {
	s.RegisterService(&Log_ServiceDesc, srv)
}

func _Log_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cafesdk.Log/Debug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Debug(ctx, req.(*LogBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cafesdk.Log/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Info(ctx, req.(*LogBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_Warn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Warn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cafesdk.Log/Warn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Warn(ctx, req.(*LogBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_Error_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Error(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cafesdk.Log/Error",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Error(ctx, req.(*LogBody))
	}
	return interceptor(ctx, in, info, handler)
}

// Log_ServiceDesc is the grpc.ServiceDesc for Log service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Log_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cafesdk.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Debug",
			Handler:    _Log_Debug_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Log_Info_Handler,
		},
		{
			MethodName: "Warn",
			Handler:    _Log_Warn_Handler,
		},
		{
			MethodName: "Error",
			Handler:    _Log_Error_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cafesdk/sdk.proto",
}
